apiVersion: apps/v1
kind: Deployment
metadata:
   name: orgchart
   namespace: thaitype-demo-corp
   labels:
      app: orgchart
spec:
   selector:
      matchLabels:
        app: orgchart
   replicas: 1
   template:
      metadata:
        annotations:
          vault.hashicorp.com/agent-inject: 'true'
          vault.hashicorp.com/agent-pre-populate-only: 'true'
          vault.hashicorp.com/agent-init-first: 'true'
          vault.hashicorp.com/role: 'internal-app'
          vault.hashicorp.com/agent-inject-secret-config: 'internal/data/database/config'
          vault.hashicorp.com/agent-inject-template-config: |
            {{- with secret "internal/data/database/config" -}}
            export DB_USER="{{ .Data.data.username }}"
            export DB_PASS="{{ .Data.data.password }}"
            {{- end -}}
        labels:
          app: orgchart
      spec:
        serviceAccountName: internal-app
        containers:
          - name: orgchart
            image: jweissig/app:0.0.1

        